services:
  specimen-app:
    image: ghcr.io/wisesakarta/specimen:${IMAGE_TAG:-latest}
    container_name: specimen-runtime-prod
    ports:
      - "8085:3000"
    restart: always
    environment:
      - NODE_ENV=production
